// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto
// Protobuf C++ Version: 4.25.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_common_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_common_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace catan {
enum ResourceType : int {
  RESOURCE_UNKNOWN = 0,
  WOOD = 1,
  BRICK = 2,
  SHEEP = 3,
  WHEAT = 4,
  ORE = 5,
  ResourceType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ResourceType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ResourceType_IsValid(int value);
extern const uint32_t ResourceType_internal_data_[];
constexpr ResourceType ResourceType_MIN = static_cast<ResourceType>(0);
constexpr ResourceType ResourceType_MAX = static_cast<ResourceType>(5);
constexpr int ResourceType_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor*
ResourceType_descriptor();
template <typename T>
const std::string& ResourceType_Name(T value) {
  static_assert(std::is_same<T, ResourceType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ResourceType_Name().");
  return ResourceType_Name(static_cast<ResourceType>(value));
}
template <>
inline const std::string& ResourceType_Name(ResourceType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ResourceType_descriptor,
                                                 0, 5>(
      static_cast<int>(value));
}
inline bool ResourceType_Parse(absl::string_view name, ResourceType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResourceType>(
      ResourceType_descriptor(), name, value);
}
enum DevCardType : int {
  None = 0,
  Monopoly = 1,
  Knight = 2,
  RoadBuilding = 3,
  YearOfPlenty = 4,
  VictoryPoint = 5,
  DevCardType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DevCardType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DevCardType_IsValid(int value);
extern const uint32_t DevCardType_internal_data_[];
constexpr DevCardType DevCardType_MIN = static_cast<DevCardType>(0);
constexpr DevCardType DevCardType_MAX = static_cast<DevCardType>(5);
constexpr int DevCardType_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor*
DevCardType_descriptor();
template <typename T>
const std::string& DevCardType_Name(T value) {
  static_assert(std::is_same<T, DevCardType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DevCardType_Name().");
  return DevCardType_Name(static_cast<DevCardType>(value));
}
template <>
inline const std::string& DevCardType_Name(DevCardType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DevCardType_descriptor,
                                                 0, 5>(
      static_cast<int>(value));
}
inline bool DevCardType_Parse(absl::string_view name, DevCardType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DevCardType>(
      DevCardType_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace catan


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::catan::ResourceType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::catan::ResourceType>() {
  return ::catan::ResourceType_descriptor();
}
template <>
struct is_proto_enum<::catan::DevCardType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::catan::DevCardType>() {
  return ::catan::DevCardType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_common_2eproto_2epb_2eh
